import type { Course } from "@/lib/types"

export const demoCourses: Course[] = [
  // Category A
  {
    id: "demo-a1",
    title: "IHO-ICA Category A Hydrographic Survey Programme",
    category: "Category A",
    description:
      "Advanced programme covering geodesy, oceanography, multibeam technology, and IHO standards for professional hydrographic surveyors.",
    duration: "12 Months",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-a2",
    title: "Advanced ECDIS & Digital Charting Certification",
    category: "Category A",
    description:
      "Training on ECDIS, ENC production, S-100 data standards, and digital hydrographic data management.",
    duration: "6 Months",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Category B
  {
    id: "demo-b1",
    title: "Basic Hydrographic Survey Course",
    category: "Category B",
    description:
      "Foundational course covering positioning systems, echo sounding, and coastal survey methods for naval and civilian personnel.",
    duration: "6 Months",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-b2",
    title: "Nautical Charting & Marine Cartography",
    category: "Category B",
    description:
      "Practical training in chart compilation, nautical symbology, and Notice to Mariners preparation using modern GIS tools.",
    duration: "4 Months",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-b3",
    title: "Coastal Zone Survey & Port Hydrography",
    category: "Category B",
    description:
      "Specialized training in shallow-water techniques, dredging surveys, and coastal navigation safety assessments.",
    duration: "3 Months",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Survey Recorder
  {
    id: "demo-sr1",
    title: "Survey Recorder – Grade I",
    category: "Survey Recorder",
    description:
      "Advanced training in multibeam data acquisition, side-scan sonar, and survey operation management.",
    duration: "8 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-sr2",
    title: "Survey Recorder – Grade II",
    category: "Survey Recorder",
    description:
      "Intermediate training in single-beam echo sounder, data logging, and survey vessel operations.",
    duration: "6 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-sr3",
    title: "Survey Recorder – Grade III",
    category: "Survey Recorder",
    description:
      "Entry-level course covering basic hydrographic terminology, equipment handling, and depth measurement principles.",
    duration: "4 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Surveyor
  {
    id: "demo-sv1",
    title: "Marine Geodesy & GNSS Applications",
    category: "Surveyor",
    description:
      "Comprehensive programme covering geodetic datums, PPK/RTK survey methods, and hydrographic survey integration.",
    duration: "10 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-sv2",
    title: "Oceanographic Data Collection & Analysis",
    category: "Surveyor",
    description:
      "Training in CTD profiling, current metering, water sampling, and maritime meteorological observations.",
    duration: "8 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  // Customized
  {
    id: "demo-c1",
    title: "Inland Waterway Survey Techniques",
    category: "Customized",
    description:
      "Tailored programme for river authorities covering bathymetry, bank erosion monitoring, and navigation channel surveys.",
    duration: "4 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-c2",
    title: "Maritime Safety & Search-and-Rescue",
    category: "Customized",
    description:
      "Specialized training in SAR coordination, GMDSS operations, and emergency response survey procedures.",
    duration: "3 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-c3",
    title: "Blue Economy & Marine Spatial Planning",
    category: "Customized",
    description:
      "Executive programme covering marine spatial data infrastructure, EEZ management, and sustainable ocean governance.",
    duration: "2 Weeks",
    brochure_url: null,
    image_url: null,
    is_published: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
